import type { FoodDbRow } from '../../types/database'

/**
 * Seed data for common foods.
 * All nutrition values per 100g serving (standardized).
 * Source: USDA FoodData Central
 *
 * Calorie validation: calories ≈ (protein_g × 4) + (carbs_g × 4) + (fat_g × 9) ± 10%
 */
export const seedFoods: Omit<FoodDbRow, 'id' | 'created_at' | 'updated_at'>[] = [
  // PROTEINS (20 items)
  {
    name: 'Chicken Breast',
    slug: 'chicken-breast',
    serving_size_g: 100,
    calories: 165,
    protein_g: 31,
    carbohydrates_total_g: 0,
    fat_total_g: 3.6,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 74,
    potassium_mg: 256,
    cholesterol_mg: 85,
    data_source: 'seed'
  },
  {
    name: 'Chicken Thigh',
    slug: 'chicken-thigh',
    serving_size_g: 100,
    calories: 209,
    protein_g: 26,
    carbohydrates_total_g: 0,
    fat_total_g: 11,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 86,
    potassium_mg: 229,
    cholesterol_mg: 93,
    data_source: 'seed'
  },
  {
    name: 'Turkey Breast',
    slug: 'turkey-breast',
    serving_size_g: 100,
    calories: 135,
    protein_g: 30,
    carbohydrates_total_g: 0,
    fat_total_g: 1,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 62,
    potassium_mg: 289,
    cholesterol_mg: 65,
    data_source: 'seed'
  },
  {
    name: 'Ground Turkey',
    slug: 'ground-turkey',
    serving_size_g: 100,
    calories: 149,
    protein_g: 28,
    carbohydrates_total_g: 0,
    fat_total_g: 3,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 70,
    potassium_mg: 280,
    cholesterol_mg: 75,
    data_source: 'seed'
  },
  {
    name: 'Salmon Atlantic',
    slug: 'salmon-atlantic',
    serving_size_g: 100,
    calories: 208,
    protein_g: 20,
    carbohydrates_total_g: 0,
    fat_total_g: 13,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 59,
    potassium_mg: 363,
    cholesterol_mg: 55,
    data_source: 'seed'
  },
  {
    name: 'Tuna Canned in Water',
    slug: 'tuna-canned-in-water',
    serving_size_g: 100,
    calories: 116,
    protein_g: 26,
    carbohydrates_total_g: 0,
    fat_total_g: 1,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 377,
    potassium_mg: 235,
    cholesterol_mg: 40,
    data_source: 'seed'
  },
  {
    name: 'Lean Beef Sirloin',
    slug: 'lean-beef-sirloin',
    serving_size_g: 100,
    calories: 154,
    protein_g: 26,
    carbohydrates_total_g: 0,
    fat_total_g: 5,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 60,
    potassium_mg: 350,
    cholesterol_mg: 70,
    data_source: 'seed'
  },
  {
    name: 'Ground Beef 93% Lean',
    slug: 'ground-beef-93-lean',
    serving_size_g: 100,
    calories: 164,
    protein_g: 23,
    carbohydrates_total_g: 0,
    fat_total_g: 7,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 70,
    potassium_mg: 320,
    cholesterol_mg: 70,
    data_source: 'seed'
  },
  {
    name: 'Egg Large',
    slug: 'egg-large',
    serving_size_g: 100,
    calories: 155,
    protein_g: 13,
    carbohydrates_total_g: 1.1,
    fat_total_g: 11,
    fiber_g: 0,
    sugar_g: 1.1,
    sodium_mg: 124,
    potassium_mg: 138,
    cholesterol_mg: 373,
    data_source: 'seed'
  },
  {
    name: 'Egg Whites',
    slug: 'egg-whites',
    serving_size_g: 100,
    calories: 52,
    protein_g: 11,
    carbohydrates_total_g: 0.7,
    fat_total_g: 0.2,
    fiber_g: 0,
    sugar_g: 0.7,
    sodium_mg: 166,
    potassium_mg: 163,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Cod Fish',
    slug: 'cod-fish',
    serving_size_g: 100,
    calories: 82,
    protein_g: 18,
    carbohydrates_total_g: 0,
    fat_total_g: 0.7,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 78,
    potassium_mg: 278,
    cholesterol_mg: 43,
    data_source: 'seed'
  },
  {
    name: 'Shrimp',
    slug: 'shrimp',
    serving_size_g: 100,
    calories: 99,
    protein_g: 24,
    carbohydrates_total_g: 0.2,
    fat_total_g: 0.3,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 120,
    potassium_mg: 220,
    cholesterol_mg: 150,
    data_source: 'seed'
  },
  {
    name: 'Tilapia',
    slug: 'tilapia',
    serving_size_g: 100,
    calories: 96,
    protein_g: 20,
    carbohydrates_total_g: 0,
    fat_total_g: 1.7,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 52,
    potassium_mg: 380,
    cholesterol_mg: 50,
    data_source: 'seed'
  },
  {
    name: 'Pork Tenderloin',
    slug: 'pork-tenderloin',
    serving_size_g: 100,
    calories: 143,
    protein_g: 22,
    carbohydrates_total_g: 0,
    fat_total_g: 5,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 60,
    potassium_mg: 420,
    cholesterol_mg: 70,
    data_source: 'seed'
  },
  {
    name: 'Ham Lean',
    slug: 'ham-lean',
    serving_size_g: 100,
    calories: 122,
    protein_g: 21,
    carbohydrates_total_g: 1.5,
    fat_total_g: 3,
    fiber_g: 0,
    sugar_g: 1,
    sodium_mg: 1050,
    potassium_mg: 300,
    cholesterol_mg: 55,
    data_source: 'seed'
  },
  {
    name: 'Bacon Turkey',
    slug: 'bacon-turkey',
    serving_size_g: 100,
    calories: 226,
    protein_g: 26,
    carbohydrates_total_g: 1.5,
    fat_total_g: 12,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 1500,
    potassium_mg: 280,
    cholesterol_mg: 65,
    data_source: 'seed'
  },
  {
    name: 'Lamb Leg',
    slug: 'lamb-leg',
    serving_size_g: 100,
    calories: 175,
    protein_g: 24,
    carbohydrates_total_g: 0,
    fat_total_g: 8,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 70,
    potassium_mg: 310,
    cholesterol_mg: 80,
    data_source: 'seed'
  },
  {
    name: 'Bison',
    slug: 'bison',
    serving_size_g: 100,
    calories: 143,
    protein_g: 28,
    carbohydrates_total_g: 0,
    fat_total_g: 2.5,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 65,
    potassium_mg: 350,
    cholesterol_mg: 70,
    data_source: 'seed'
  },
  {
    name: 'Venison',
    slug: 'venison',
    serving_size_g: 100,
    calories: 150,
    protein_g: 30,
    carbohydrates_total_g: 0,
    fat_total_g: 3,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 60,
    potassium_mg: 380,
    cholesterol_mg: 80,
    data_source: 'seed'
  },
  {
    name: 'Sardines Canned',
    slug: 'sardines-canned',
    serving_size_g: 100,
    calories: 208,
    protein_g: 25,
    carbohydrates_total_g: 0,
    fat_total_g: 11,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 420,
    potassium_mg: 397,
    cholesterol_mg: 70,
    data_source: 'seed'
  },

  // CARBOHYDRATES (25 items)
  {
    name: 'Brown Rice Cooked',
    slug: 'brown-rice-cooked',
    serving_size_g: 100,
    calories: 112,
    protein_g: 2.6,
    carbohydrates_total_g: 24,
    fat_total_g: 0.9,
    fiber_g: 1.8,
    sugar_g: 0.4,
    sodium_mg: 5,
    potassium_mg: 43,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'White Rice Cooked',
    slug: 'white-rice-cooked',
    serving_size_g: 100,
    calories: 130,
    protein_g: 2.7,
    carbohydrates_total_g: 28,
    fat_total_g: 0.3,
    fiber_g: 0.4,
    sugar_g: 0.1,
    sodium_mg: 5,
    potassium_mg: 35,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Potato Boiled',
    slug: 'potato-boiled',
    serving_size_g: 100,
    calories: 87,
    protein_g: 1.9,
    carbohydrates_total_g: 20,
    fat_total_g: 0.1,
    fiber_g: 1.8,
    sugar_g: 0.9,
    sodium_mg: 5,
    potassium_mg: 328,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Sweet Potato Boiled',
    slug: 'sweet-potato-boiled',
    serving_size_g: 100,
    calories: 86,
    protein_g: 1.6,
    carbohydrates_total_g: 20,
    fat_total_g: 0.1,
    fiber_g: 3,
    sugar_g: 4.2,
    sodium_mg: 5,
    potassium_mg: 230,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Oats Rolled Dry',
    slug: 'oats-rolled-dry',
    serving_size_g: 100,
    calories: 389,
    protein_g: 16.9,
    carbohydrates_total_g: 66,
    fat_total_g: 6.9,
    fiber_g: 10.6,
    sugar_g: 0.6,
    sodium_mg: 2,
    potassium_mg: 429,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Oatmeal Cooked',
    slug: 'oatmeal-cooked',
    serving_size_g: 100,
    calories: 71,
    protein_g: 2.5,
    carbohydrates_total_g: 12,
    fat_total_g: 1.4,
    fiber_g: 1.7,
    sugar_g: 0.6,
    sodium_mg: 49,
    potassium_mg: 61,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Quinoa Cooked',
    slug: 'quinoa-cooked',
    serving_size_g: 100,
    calories: 120,
    protein_g: 4.4,
    carbohydrates_total_g: 21,
    fat_total_g: 1.9,
    fiber_g: 2.8,
    sugar_g: 0.9,
    sodium_mg: 7,
    potassium_mg: 172,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Whole Wheat Bread',
    slug: 'whole-wheat-bread',
    serving_size_g: 100,
    calories: 247,
    protein_g: 13,
    carbohydrates_total_g: 41,
    fat_total_g: 3.4,
    fiber_g: 6,
    sugar_g: 5,
    sodium_mg: 380,
    potassium_mg: 230,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'White Bread',
    slug: 'white-bread',
    serving_size_g: 100,
    calories: 265,
    protein_g: 9,
    carbohydrates_total_g: 49,
    fat_total_g: 3.2,
    fiber_g: 2.7,
    sugar_g: 5,
    sodium_mg: 420,
    potassium_mg: 115,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pasta Whole Wheat Cooked',
    slug: 'pasta-whole-wheat-cooked',
    serving_size_g: 100,
    calories: 124,
    protein_g: 5.3,
    carbohydrates_total_g: 26,
    fat_total_g: 0.5,
    fiber_g: 3.8,
    sugar_g: 0.6,
    sodium_mg: 5,
    potassium_mg: 44,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pasta White Cooked',
    slug: 'pasta-white-cooked',
    serving_size_g: 100,
    calories: 131,
    protein_g: 5,
    carbohydrates_total_g: 25,
    fat_total_g: 1.1,
    fiber_g: 1.5,
    sugar_g: 0.6,
    sodium_mg: 6,
    potassium_mg: 44,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Couscous Cooked',
    slug: 'couscous-cooked',
    serving_size_g: 100,
    calories: 112,
    protein_g: 3.8,
    carbohydrates_total_g: 23,
    fat_total_g: 0.2,
    fiber_g: 1.4,
    sugar_g: 0.4,
    sodium_mg: 5,
    potassium_mg: 58,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Corn Sweet Cooked',
    slug: 'corn-sweet-cooked',
    serving_size_g: 100,
    calories: 96,
    protein_g: 3.4,
    carbohydrates_total_g: 21,
    fat_total_g: 1.5,
    fiber_g: 2.4,
    sugar_g: 4.5,
    sodium_mg: 2,
    potassium_mg: 270,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Peas Green Cooked',
    slug: 'peas-green-cooked',
    serving_size_g: 100,
    calories: 84,
    protein_g: 5.4,
    carbohydrates_total_g: 14,
    fat_total_g: 0.4,
    fiber_g: 5.5,
    sugar_g: 4,
    sodium_mg: 5,
    potassium_mg: 244,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Lentils Cooked',
    slug: 'lentils-cooked',
    serving_size_g: 100,
    calories: 116,
    protein_g: 9,
    carbohydrates_total_g: 20,
    fat_total_g: 0.4,
    fiber_g: 7.9,
    sugar_g: 1.8,
    sodium_mg: 2,
    potassium_mg: 369,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Black Beans Cooked',
    slug: 'black-beans-cooked',
    serving_size_g: 100,
    calories: 132,
    protein_g: 8.9,
    carbohydrates_total_g: 24,
    fat_total_g: 0.5,
    fiber_g: 6.9,
    sugar_g: 0.5,
    sodium_mg: 5,
    potassium_mg: 355,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Chickpeas Cooked',
    slug: 'chickpeas-cooked',
    serving_size_g: 100,
    calories: 164,
    protein_g: 8.9,
    carbohydrates_total_g: 27,
    fat_total_g: 2.6,
    fiber_g: 7.6,
    sugar_g: 4.8,
    sodium_mg: 5,
    potassium_mg: 291,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Kidney Beans Cooked',
    slug: 'kidney-beans-cooked',
    serving_size_g: 100,
    calories: 127,
    protein_g: 8.7,
    carbohydrates_total_g: 23,
    fat_total_g: 0.5,
    fiber_g: 6.4,
    sugar_g: 0.3,
    sodium_mg: 5,
    potassium_mg: 405,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pinto Beans Cooked',
    slug: 'pinto-beans-cooked',
    serving_size_g: 100,
    calories: 143,
    protein_g: 9,
    carbohydrates_total_g: 26,
    fat_total_g: 0.7,
    fiber_g: 9,
    sugar_g: 0.6,
    sodium_mg: 5,
    potassium_mg: 436,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Barley Cooked',
    slug: 'barley-cooked',
    serving_size_g: 100,
    calories: 123,
    protein_g: 2.3,
    carbohydrates_total_g: 28,
    fat_total_g: 0.4,
    fiber_g: 3.8,
    sugar_g: 0.8,
    sodium_mg: 5,
    potassium_mg: 96,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Bulgur Cooked',
    slug: 'bulgur-cooked',
    serving_size_g: 100,
    calories: 83,
    protein_g: 3.1,
    carbohydrates_total_g: 19,
    fat_total_g: 0.2,
    fiber_g: 4.5,
    sugar_g: 0.2,
    sodium_mg: 5,
    potassium_mg: 98,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Millet Cooked',
    slug: 'millet-cooked',
    serving_size_g: 100,
    calories: 119,
    protein_g: 3.5,
    carbohydrates_total_g: 25,
    fat_total_g: 1,
    fiber_g: 1.5,
    sugar_g: 0.2,
    sodium_mg: 5,
    potassium_mg: 62,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Soba Noodles Cooked',
    slug: 'soba-noodles-cooked',
    serving_size_g: 100,
    calories: 99,
    protein_g: 5,
    carbohydrates_total_g: 21,
    fat_total_g: 0.1,
    fiber_g: 2,
    sugar_g: 0.5,
    sodium_mg: 200,
    potassium_mg: 60,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Tortilla Flour',
    slug: 'tortilla-flour',
    serving_size_g: 100,
    calories: 295,
    protein_g: 8,
    carbohydrates_total_g: 49,
    fat_total_g: 8,
    fiber_g: 2.7,
    sugar_g: 1.5,
    sodium_mg: 400,
    potassium_mg: 150,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Bagel Plain',
    slug: 'bagel-plain',
    serving_size_g: 100,
    calories: 250,
    protein_g: 10,
    carbohydrates_total_g: 50,
    fat_total_g: 1.5,
    fiber_g: 2.5,
    sugar_g: 5,
    sodium_mg: 450,
    potassium_mg: 100,
    cholesterol_mg: 0,
    data_source: 'seed'
  },

  // VEGETABLES (20 items)
  {
    name: 'Broccoli Raw',
    slug: 'broccoli-raw',
    serving_size_g: 100,
    calories: 34,
    protein_g: 2.8,
    carbohydrates_total_g: 7,
    fat_total_g: 0.4,
    fiber_g: 2.6,
    sugar_g: 1.5,
    sodium_mg: 33,
    potassium_mg: 316,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Spinach Raw',
    slug: 'spinach-raw',
    serving_size_g: 100,
    calories: 23,
    protein_g: 2.9,
    carbohydrates_total_g: 3.6,
    fat_total_g: 0.4,
    fiber_g: 2.2,
    sugar_g: 0.4,
    sodium_mg: 79,
    potassium_mg: 558,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Carrot Raw',
    slug: 'carrot-raw',
    serving_size_g: 100,
    calories: 41,
    protein_g: 0.9,
    carbohydrates_total_g: 10,
    fat_total_g: 0.2,
    fiber_g: 2.8,
    sugar_g: 4.7,
    sodium_mg: 69,
    potassium_mg: 320,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Tomato Raw',
    slug: 'tomato-raw',
    serving_size_g: 100,
    calories: 18,
    protein_g: 0.9,
    carbohydrates_total_g: 3.9,
    fat_total_g: 0.2,
    fiber_g: 1.2,
    sugar_g: 2.6,
    sodium_mg: 5,
    potassium_mg: 237,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Avocado Raw',
    slug: 'avocado-raw',
    serving_size_g: 100,
    calories: 160,
    protein_g: 2,
    carbohydrates_total_g: 8.5,
    fat_total_g: 15,
    fiber_g: 6.7,
    sugar_g: 0.3,
    sodium_mg: 7,
    potassium_mg: 485,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Cauliflower Raw',
    slug: 'cauliflower-raw',
    serving_size_g: 100,
    calories: 25,
    protein_g: 1.9,
    carbohydrates_total_g: 5,
    fat_total_g: 0.3,
    fiber_g: 2,
    sugar_g: 2,
    sodium_mg: 30,
    potassium_mg: 299,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Asparagus Raw',
    slug: 'asparagus-raw',
    serving_size_g: 100,
    calories: 20,
    protein_g: 2.2,
    carbohydrates_total_g: 3.9,
    fat_total_g: 0.1,
    fiber_g: 2.1,
    sugar_g: 1.9,
    sodium_mg: 2,
    potassium_mg: 202,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Bell Pepper Red',
    slug: 'bell-pepper-red',
    serving_size_g: 100,
    calories: 31,
    protein_g: 1,
    carbohydrates_total_g: 6,
    fat_total_g: 0.3,
    fiber_g: 2.1,
    sugar_g: 4.2,
    sodium_mg: 4,
    potassium_mg: 211,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Bell Pepper Green',
    slug: 'bell-pepper-green',
    serving_size_g: 100,
    calories: 20,
    protein_g: 0.9,
    carbohydrates_total_g: 4.6,
    fat_total_g: 0.2,
    fiber_g: 1.7,
    sugar_g: 2.4,
    sodium_mg: 3,
    potassium_mg: 175,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Cucumber Raw',
    slug: 'cucumber-raw',
    serving_size_g: 100,
    calories: 16,
    protein_g: 0.7,
    carbohydrates_total_g: 4,
    fat_total_g: 0.1,
    fiber_g: 0.5,
    sugar_g: 1.7,
    sodium_mg: 2,
    potassium_mg: 147,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Lettuce Romaine',
    slug: 'lettuce-romaine',
    serving_size_g: 100,
    calories: 17,
    protein_g: 1.4,
    carbohydrates_total_g: 3.3,
    fat_total_g: 0.3,
    fiber_g: 2.1,
    sugar_g: 1.2,
    sodium_mg: 8,
    potassium_mg: 247,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Kale Raw',
    slug: 'kale-raw',
    serving_size_g: 100,
    calories: 35,
    protein_g: 2.9,
    carbohydrates_total_g: 5,
    fat_total_g: 0.6,
    fiber_g: 2,
    sugar_g: 1,
    sodium_mg: 33,
    potassium_mg: 299,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Zucchini Raw',
    slug: 'zucchini-raw',
    serving_size_g: 100,
    calories: 17,
    protein_g: 1.2,
    carbohydrates_total_g: 3.1,
    fat_total_g: 0.3,
    fiber_g: 1,
    sugar_g: 2.5,
    sodium_mg: 8,
    potassium_mg: 261,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Mushrooms Raw',
    slug: 'mushrooms-raw',
    serving_size_g: 100,
    calories: 22,
    protein_g: 3.1,
    carbohydrates_total_g: 3.3,
    fat_total_g: 0.3,
    fiber_g: 1,
    sugar_g: 2,
    sodium_mg: 5,
    potassium_mg: 318,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Onion Raw',
    slug: 'onion-raw',
    serving_size_g: 100,
    calories: 40,
    protein_g: 1.1,
    carbohydrates_total_g: 9.3,
    fat_total_g: 0.1,
    fiber_g: 1.7,
    sugar_g: 4.2,
    sodium_mg: 4,
    potassium_mg: 146,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Garlic Raw',
    slug: 'garlic-raw',
    serving_size_g: 100,
    calories: 149,
    protein_g: 6.4,
    carbohydrates_total_g: 33,
    fat_total_g: 0.5,
    fiber_g: 2.1,
    sugar_g: 1,
    sodium_mg: 17,
    potassium_mg: 401,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Brussels Sprouts Raw',
    slug: 'brussels-sprouts-raw',
    serving_size_g: 100,
    calories: 43,
    protein_g: 3.4,
    carbohydrates_total_g: 9,
    fat_total_g: 0.8,
    fiber_g: 3.8,
    sugar_g: 2.2,
    sodium_mg: 21,
    potassium_mg: 389,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Green Beans Raw',
    slug: 'green-beans-raw',
    serving_size_g: 100,
    calories: 31,
    protein_g: 1.8,
    carbohydrates_total_g: 7,
    fat_total_g: 0.1,
    fiber_g: 2.7,
    sugar_g: 3.3,
    sodium_mg: 6,
    potassium_mg: 209,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Celery Raw',
    slug: 'celery-raw',
    serving_size_g: 100,
    calories: 14,
    protein_g: 0.7,
    carbohydrates_total_g: 3,
    fat_total_g: 0.1,
    fiber_g: 1.6,
    sugar_g: 1.3,
    sodium_mg: 80,
    potassium_mg: 260,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Eggplant Raw',
    slug: 'eggplant-raw',
    serving_size_g: 100,
    calories: 25,
    protein_g: 1,
    carbohydrates_total_g: 6,
    fat_total_g: 0.2,
    fiber_g: 3,
    sugar_g: 2,
    sodium_mg: 2,
    potassium_mg: 229,
    cholesterol_mg: 0,
    data_source: 'seed'
  },

  // FRUITS (15 items)
  {
    name: 'Banana',
    slug: 'banana',
    serving_size_g: 100,
    calories: 89,
    protein_g: 1.1,
    carbohydrates_total_g: 23,
    fat_total_g: 0.3,
    fiber_g: 2.6,
    sugar_g: 12,
    sodium_mg: 1,
    potassium_mg: 358,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Apple with Skin',
    slug: 'apple-with-skin',
    serving_size_g: 100,
    calories: 52,
    protein_g: 0.3,
    carbohydrates_total_g: 14,
    fat_total_g: 0.2,
    fiber_g: 2.4,
    sugar_g: 10,
    sodium_mg: 1,
    potassium_mg: 107,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Blueberries Raw',
    slug: 'blueberries-raw',
    serving_size_g: 100,
    calories: 57,
    protein_g: 0.7,
    carbohydrates_total_g: 14,
    fat_total_g: 0.3,
    fiber_g: 2.4,
    sugar_g: 10,
    sodium_mg: 1,
    potassium_mg: 77,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Strawberries Raw',
    slug: 'strawberries-raw',
    serving_size_g: 100,
    calories: 32,
    protein_g: 0.7,
    carbohydrates_total_g: 7.7,
    fat_total_g: 0.3,
    fiber_g: 2,
    sugar_g: 4.9,
    sodium_mg: 1,
    potassium_mg: 153,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Orange Raw',
    slug: 'orange-raw',
    serving_size_g: 100,
    calories: 47,
    protein_g: 0.9,
    carbohydrates_total_g: 12,
    fat_total_g: 0.1,
    fiber_g: 2.4,
    sugar_g: 9,
    sodium_mg: 0,
    potassium_mg: 181,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Grapes Raw',
    slug: 'grapes-raw',
    serving_size_g: 100,
    calories: 69,
    protein_g: 0.7,
    carbohydrates_total_g: 18,
    fat_total_g: 0.2,
    fiber_g: 0.9,
    sugar_g: 16,
    sodium_mg: 2,
    potassium_mg: 191,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Mango Raw',
    slug: 'mango-raw',
    serving_size_g: 100,
    calories: 60,
    protein_g: 0.8,
    carbohydrates_total_g: 15,
    fat_total_g: 0.4,
    fiber_g: 1.6,
    sugar_g: 14,
    sodium_mg: 1,
    potassium_mg: 168,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pineapple Raw',
    slug: 'pineapple-raw',
    serving_size_g: 100,
    calories: 50,
    protein_g: 0.5,
    carbohydrates_total_g: 13,
    fat_total_g: 0.1,
    fiber_g: 1.4,
    sugar_g: 10,
    sodium_mg: 1,
    potassium_mg: 109,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Peach Raw',
    slug: 'peach-raw',
    serving_size_g: 100,
    calories: 39,
    protein_g: 0.9,
    carbohydrates_total_g: 10,
    fat_total_g: 0.3,
    fiber_g: 1.5,
    sugar_g: 8.4,
    sodium_mg: 0,
    potassium_mg: 122,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pear Raw',
    slug: 'pear-raw',
    serving_size_g: 100,
    calories: 57,
    protein_g: 0.4,
    carbohydrates_total_g: 15,
    fat_total_g: 0.1,
    fiber_g: 3.1,
    sugar_g: 10,
    sodium_mg: 1,
    potassium_mg: 116,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Watermelon Raw',
    slug: 'watermelon-raw',
    serving_size_g: 100,
    calories: 30,
    protein_g: 0.6,
    carbohydrates_total_g: 8,
    fat_total_g: 0.2,
    fiber_g: 0.4,
    sugar_g: 6,
    sodium_mg: 1,
    potassium_mg: 112,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Raspberries Raw',
    slug: 'raspberries-raw',
    serving_size_g: 100,
    calories: 52,
    protein_g: 1.2,
    carbohydrates_total_g: 12,
    fat_total_g: 0.7,
    fiber_g: 6.5,
    sugar_g: 4.4,
    sodium_mg: 1,
    potassium_mg: 151,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Blackberries Raw',
    slug: 'blackberries-raw',
    serving_size_g: 100,
    calories: 43,
    protein_g: 1.4,
    carbohydrates_total_g: 10,
    fat_total_g: 0.5,
    fiber_g: 5.3,
    sugar_g: 4.9,
    sodium_mg: 1,
    potassium_mg: 162,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Lemon Raw',
    slug: 'lemon-raw',
    serving_size_g: 100,
    calories: 29,
    protein_g: 1.1,
    carbohydrates_total_g: 9,
    fat_total_g: 0.3,
    fiber_g: 2.8,
    sugar_g: 2.5,
    sodium_mg: 2,
    potassium_mg: 138,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Lime Raw',
    slug: 'lime-raw',
    serving_size_g: 100,
    calories: 30,
    protein_g: 0.7,
    carbohydrates_total_g: 11,
    fat_total_g: 0.2,
    fiber_g: 2.8,
    sugar_g: 1.7,
    sodium_mg: 2,
    potassium_mg: 102,
    cholesterol_mg: 0,
    data_source: 'seed'
  },

  // DAIRY (15 items)
  {
    name: 'Milk Whole',
    slug: 'milk-whole',
    serving_size_g: 100,
    calories: 61,
    protein_g: 3.2,
    carbohydrates_total_g: 4.8,
    fat_total_g: 3.3,
    fiber_g: 0,
    sugar_g: 4.8,
    sodium_mg: 43,
    potassium_mg: 132,
    cholesterol_mg: 10,
    data_source: 'seed'
  },
  {
    name: 'Milk 2% Reduced Fat',
    slug: 'milk-2-reduced-fat',
    serving_size_g: 100,
    calories: 50,
    protein_g: 3.3,
    carbohydrates_total_g: 4.8,
    fat_total_g: 1.9,
    fiber_g: 0,
    sugar_g: 4.8,
    sodium_mg: 42,
    potassium_mg: 140,
    cholesterol_mg: 8,
    data_source: 'seed'
  },
  {
    name: 'Milk Skim Nonfat',
    slug: 'milk-skim-nonfat',
    serving_size_g: 100,
    calories: 35,
    protein_g: 3.4,
    carbohydrates_total_g: 5,
    fat_total_g: 0.1,
    fiber_g: 0,
    sugar_g: 5,
    sodium_mg: 42,
    potassium_mg: 156,
    cholesterol_mg: 2,
    data_source: 'seed'
  },
  {
    name: 'Greek Yogurt Nonfat',
    slug: 'greek-yogurt-nonfat',
    serving_size_g: 100,
    calories: 59,
    protein_g: 10,
    carbohydrates_total_g: 3.6,
    fat_total_g: 0.4,
    fiber_g: 0,
    sugar_g: 3.6,
    sodium_mg: 36,
    potassium_mg: 141,
    cholesterol_mg: 2,
    data_source: 'seed'
  },
  {
    name: 'Greek Yogurt Whole',
    slug: 'greek-yogurt-whole',
    serving_size_g: 100,
    calories: 97,
    protein_g: 9,
    carbohydrates_total_g: 3.6,
    fat_total_g: 5,
    fiber_g: 0,
    sugar_g: 3.6,
    sodium_mg: 56,
    potassium_mg: 120,
    cholesterol_mg: 15,
    data_source: 'seed'
  },
  {
    name: 'Cottage Cheese Low Fat',
    slug: 'cottage-cheese-low-fat',
    serving_size_g: 100,
    calories: 72,
    protein_g: 12,
    carbohydrates_total_g: 3,
    fat_total_g: 1.1,
    fiber_g: 0,
    sugar_g: 2.2,
    sodium_mg: 380,
    potassium_mg: 110,
    cholesterol_mg: 8,
    data_source: 'seed'
  },
  {
    name: 'Cottage Cheese Full Fat',
    slug: 'cottage-cheese-full-fat',
    serving_size_g: 100,
    calories: 98,
    protein_g: 11,
    carbohydrates_total_g: 3.4,
    fat_total_g: 4.3,
    fiber_g: 0,
    sugar_g: 2.7,
    sodium_mg: 364,
    potassium_mg: 104,
    cholesterol_mg: 17,
    data_source: 'seed'
  },
  {
    name: 'Cheddar Cheese',
    slug: 'cheddar-cheese',
    serving_size_g: 100,
    calories: 403,
    protein_g: 25,
    carbohydrates_total_g: 1.3,
    fat_total_g: 33,
    fiber_g: 0,
    sugar_g: 0.5,
    sodium_mg: 621,
    potassium_mg: 76,
    cholesterol_mg: 99,
    data_source: 'seed'
  },
  {
    name: 'Mozzarella Cheese Whole',
    slug: 'mozzarella-cheese-whole',
    serving_size_g: 100,
    calories: 318,
    protein_g: 22,
    carbohydrates_total_g: 2.2,
    fat_total_g: 25,
    fiber_g: 0,
    sugar_g: 1,
    sodium_mg: 576,
    potassium_mg: 65,
    cholesterol_mg: 78,
    data_source: 'seed'
  },
  {
    name: 'Swiss Cheese',
    slug: 'swiss-cheese',
    serving_size_g: 100,
    calories: 393,
    protein_g: 27,
    carbohydrates_total_g: 1.4,
    fat_total_g: 31,
    fiber_g: 0,
    sugar_g: 0.5,
    sodium_mg: 54,
    potassium_mg: 93,
    cholesterol_mg: 92,
    data_source: 'seed'
  },
  {
    name: 'Parmesan Cheese',
    slug: 'parmesan-cheese',
    serving_size_g: 100,
    calories: 431,
    protein_g: 38,
    carbohydrates_total_g: 3.2,
    fat_total_g: 29,
    fiber_g: 0,
    sugar_g: 0.5,
    sodium_mg: 1500,
    potassium_mg: 92,
    cholesterol_mg: 100,
    data_source: 'seed'
  },
  {
    name: 'Feta Cheese',
    slug: 'feta-cheese',
    serving_size_g: 100,
    calories: 265,
    protein_g: 14,
    carbohydrates_total_g: 4,
    fat_total_g: 21,
    fiber_g: 0,
    sugar_g: 4,
    sodium_mg: 1116,
    potassium_mg: 62,
    cholesterol_mg: 70,
    data_source: 'seed'
  },
  {
    name: 'Ricotta Cheese Whole',
    slug: 'ricotta-cheese-whole',
    serving_size_g: 100,
    calories: 174,
    protein_g: 11,
    carbohydrates_total_g: 3,
    fat_total_g: 13,
    fiber_g: 0,
    sugar_g: 0.5,
    sodium_mg: 84,
    potassium_mg: 105,
    cholesterol_mg: 51,
    data_source: 'seed'
  },
  {
    name: 'Cream Cheese',
    slug: 'cream-cheese',
    serving_size_g: 100,
    calories: 342,
    protein_g: 6,
    carbohydrates_total_g: 4,
    fat_total_g: 34,
    fiber_g: 0,
    sugar_g: 3,
    sodium_mg: 320,
    potassium_mg: 132,
    cholesterol_mg: 105,
    data_source: 'seed'
  },
  {
    name: 'Butter Salted',
    slug: 'butter-salted',
    serving_size_g: 100,
    calories: 717,
    protein_g: 0.9,
    carbohydrates_total_g: 0.1,
    fat_total_g: 81,
    fiber_g: 0,
    sugar_g: 0.1,
    sodium_mg: 643,
    potassium_mg: 16,
    cholesterol_mg: 215,
    data_source: 'seed'
  },

  // NUTS AND SEEDS (15 items)
  {
    name: 'Almonds Raw',
    slug: 'almonds-raw',
    serving_size_g: 100,
    calories: 579,
    protein_g: 21,
    carbohydrates_total_g: 22,
    fat_total_g: 50,
    fiber_g: 12,
    sugar_g: 4,
    sodium_mg: 1,
    potassium_mg: 733,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Walnuts Raw',
    slug: 'walnuts-raw',
    serving_size_g: 100,
    calories: 654,
    protein_g: 15,
    carbohydrates_total_g: 14,
    fat_total_g: 65,
    fiber_g: 6.7,
    sugar_g: 2.6,
    sodium_mg: 2,
    potassium_mg: 441,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Peanuts Raw',
    slug: 'peanuts-raw',
    serving_size_g: 100,
    calories: 567,
    protein_g: 26,
    carbohydrates_total_g: 16,
    fat_total_g: 49,
    fiber_g: 8.5,
    sugar_g: 4,
    sodium_mg: 6,
    potassium_mg: 705,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Peanut Butter',
    slug: 'peanut-butter',
    serving_size_g: 100,
    calories: 588,
    protein_g: 25,
    carbohydrates_total_g: 20,
    fat_total_g: 50,
    fiber_g: 6,
    sugar_g: 9,
    sodium_mg: 400,
    potassium_mg: 649,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Cashews Raw',
    slug: 'cashews-raw',
    serving_size_g: 100,
    calories: 553,
    protein_g: 18,
    carbohydrates_total_g: 30,
    fat_total_g: 44,
    fiber_g: 3.3,
    sugar_g: 6,
    sodium_mg: 12,
    potassium_mg: 660,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pecans Raw',
    slug: 'pecans-raw',
    serving_size_g: 100,
    calories: 691,
    protein_g: 9,
    carbohydrates_total_g: 14,
    fat_total_g: 72,
    fiber_g: 9.6,
    sugar_g: 4,
    sodium_mg: 0,
    potassium_mg: 410,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pistachios Raw',
    slug: 'pistachios-raw',
    serving_size_g: 100,
    calories: 560,
    protein_g: 20,
    carbohydrates_total_g: 28,
    fat_total_g: 45,
    fiber_g: 10,
    sugar_g: 8,
    sodium_mg: 1,
    potassium_mg: 1025,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Macadamia Nuts Raw',
    slug: 'macadamia-nuts-raw',
    serving_size_g: 100,
    calories: 718,
    protein_g: 8,
    carbohydrates_total_g: 14,
    fat_total_g: 76,
    fiber_g: 8.6,
    sugar_g: 4,
    sodium_mg: 5,
    potassium_mg: 368,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Hazelnuts Raw',
    slug: 'hazelnuts-raw',
    serving_size_g: 100,
    calories: 628,
    protein_g: 15,
    carbohydrates_total_g: 17,
    fat_total_g: 61,
    fiber_g: 9.4,
    sugar_g: 4,
    sodium_mg: 0,
    potassium_mg: 680,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Brazil Nuts Raw',
    slug: 'brazil-nuts-raw',
    serving_size_g: 100,
    calories: 659,
    protein_g: 14,
    carbohydrates_total_g: 12,
    fat_total_g: 67,
    fiber_g: 7.5,
    sugar_g: 2.3,
    sodium_mg: 3,
    potassium_mg: 659,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Chia Seeds',
    slug: 'chia-seeds',
    serving_size_g: 100,
    calories: 486,
    protein_g: 17,
    carbohydrates_total_g: 42,
    fat_total_g: 31,
    fiber_g: 34,
    sugar_g: 0,
    sodium_mg: 16,
    potassium_mg: 407,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Flax Seeds',
    slug: 'flax-seeds',
    serving_size_g: 100,
    calories: 534,
    protein_g: 18,
    carbohydrates_total_g: 29,
    fat_total_g: 42,
    fiber_g: 27,
    sugar_g: 2,
    sodium_mg: 30,
    potassium_mg: 813,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Pumpkin Seeds',
    slug: 'pumpkin-seeds',
    serving_size_g: 100,
    calories: 559,
    protein_g: 30,
    carbohydrates_total_g: 10,
    fat_total_g: 49,
    fiber_g: 6,
    sugar_g: 1.4,
    sodium_mg: 7,
    potassium_mg: 809,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Sunflower Seeds',
    slug: 'sunflower-seeds',
    serving_size_g: 100,
    calories: 584,
    protein_g: 21,
    carbohydrates_total_g: 20,
    fat_total_g: 51,
    fiber_g: 8.6,
    sugar_g: 3,
    sodium_mg: 3,
    potassium_mg: 645,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Sesame Seeds',
    slug: 'sesame-seeds',
    serving_size_g: 100,
    calories: 573,
    protein_g: 17,
    carbohydrates_total_g: 23,
    fat_total_g: 50,
    fiber_g: 11,
    sugar_g: 0.3,
    sodium_mg: 11,
    potassium_mg: 468,
    cholesterol_mg: 0,
    data_source: 'seed'
  },

  // ADDITIONAL COMMON FOODS (15 items to reach 120 total)
  {
    name: 'Honey Raw',
    slug: 'honey-raw',
    serving_size_g: 100,
    calories: 304,
    protein_g: 0.3,
    carbohydrates_total_g: 82,
    fat_total_g: 0,
    fiber_g: 0.2,
    sugar_g: 82,
    sodium_mg: 4,
    potassium_mg: 52,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Olive Oil',
    slug: 'olive-oil',
    serving_size_g: 100,
    calories: 884,
    protein_g: 0,
    carbohydrates_total_g: 0,
    fat_total_g: 100,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 2,
    potassium_mg: 1,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Coconut Oil',
    slug: 'coconut-oil',
    serving_size_g: 100,
    calories: 862,
    protein_g: 0,
    carbohydrates_total_g: 0,
    fat_total_g: 100,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Canola Oil',
    slug: 'canola-oil',
    serving_size_g: 100,
    calories: 884,
    protein_g: 0,
    carbohydrates_total_g: 0,
    fat_total_g: 100,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 0,
    potassium_mg: 0,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Maple Syrup',
    slug: 'maple-syrup',
    serving_size_g: 100,
    calories: 260,
    protein_g: 0,
    carbohydrates_total_g: 67,
    fat_total_g: 0.1,
    fiber_g: 0,
    sugar_g: 60,
    sodium_mg: 7,
    potassium_mg: 212,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Dark Chocolate 70-85%',
    slug: 'dark-chocolate-70-85',
    serving_size_g: 100,
    calories: 598,
    protein_g: 7.8,
    carbohydrates_total_g: 46,
    fat_total_g: 43,
    fiber_g: 11,
    sugar_g: 24,
    sodium_mg: 24,
    potassium_mg: 715,
    cholesterol_mg: 1,
    data_source: 'seed'
  },
  {
    name: 'Brown Sugar',
    slug: 'brown-sugar',
    serving_size_g: 100,
    calories: 380,
    protein_g: 0,
    carbohydrates_total_g: 98,
    fat_total_g: 0,
    fiber_g: 0,
    sugar_g: 97,
    sodium_mg: 15,
    potassium_mg: 133,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'White Sugar',
    slug: 'white-sugar',
    serving_size_g: 100,
    calories: 387,
    protein_g: 0,
    carbohydrates_total_g: 100,
    fat_total_g: 0,
    fiber_g: 0,
    sugar_g: 100,
    sodium_mg: 1,
    potassium_mg: 2,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Tofu Firm',
    slug: 'tofu-firm',
    serving_size_g: 100,
    calories: 144,
    protein_g: 17,
    carbohydrates_total_g: 3,
    fat_total_g: 9,
    fiber_g: 2,
    sugar_g: 1,
    sodium_mg: 10,
    potassium_mg: 146,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Tempeh',
    slug: 'tempeh',
    serving_size_g: 100,
    calories: 193,
    protein_g: 19,
    carbohydrates_total_g: 9,
    fat_total_g: 11,
    fiber_g: 6,
    sugar_g: 0,
    sodium_mg: 10,
    potassium_mg: 250,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Soy Milk Unsweetened',
    slug: 'soy-milk-unsweetened',
    serving_size_g: 100,
    calories: 33,
    protein_g: 3.3,
    carbohydrates_total_g: 2,
    fat_total_g: 1.8,
    fiber_g: 0.6,
    sugar_g: 1,
    sodium_mg: 5,
    potassium_mg: 118,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Almond Milk Unsweetened',
    slug: 'almond-milk-unsweetened',
    serving_size_g: 100,
    calories: 17,
    protein_g: 0.4,
    carbohydrates_total_g: 1,
    fat_total_g: 1.5,
    fiber_g: 0,
    sugar_g: 0,
    sodium_mg: 50,
    potassium_mg: 40,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Oat Milk Unsweetened',
    slug: 'oat-milk-unsweetened',
    serving_size_g: 100,
    calories: 38,
    protein_g: 1,
    carbohydrates_total_g: 6,
    fat_total_g: 1.5,
    fiber_g: 0.8,
    sugar_g: 4,
    sodium_mg: 35,
    potassium_mg: 90,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Coconut Milk Unsweetened',
    slug: 'coconut-milk-unsweetened',
    serving_size_g: 100,
    calories: 15,
    protein_g: 0.4,
    carbohydrates_total_g: 2,
    fat_total_g: 1,
    fiber_g: 0,
    sugar_g: 2,
    sodium_mg: 10,
    potassium_mg: 100,
    cholesterol_mg: 0,
    data_source: 'seed'
  },
  {
    name: 'Rice Cakes',
    slug: 'rice-cakes',
    serving_size_g: 100,
    calories: 391,
    protein_g: 7,
    carbohydrates_total_g: 80,
    fat_total_g: 3,
    fiber_g: 4,
    sugar_g: 2,
    sodium_mg: 400,
    potassium_mg: 150,
    cholesterol_mg: 0,
    data_source: 'seed'
  }
]
